from __future__ import annotations

import json
from pathlib import Path

from src.review.schema import EvidencePack, PolicyClause


def get_evidence_pack_registry() -> dict[str, EvidencePack]:
    registry = {
        'construction_org.base': EvidencePack(
            id='construction_org.base',
            version='1.0.0',
            docTypes=['construction_org'],
            applicability='construction_org',
            clauses=[
                PolicyClause(
                    id='construction_org_structure',
                    sourceId='construction-《建筑施工组织设计规范》GB/T 50502-2009',
                    title='施工组织设计结构完整性',
                    excerpt='施工组织设计应覆盖工程概况、部署、进度、资源、安全、应急和平面布置等核心章节，并保持结构清晰。',
                    forceLevel='should',
                    applicability='construction_org',
                ),
                PolicyClause(
                    id='construction_org_schedule_resource',
                    sourceId='construction-《建筑施工组织设计规范》GB/T 50502-2009',
                    title='进度与资源协调',
                    excerpt='施工部署、资源投入和工期窗口应相互匹配，尤其要控制交叉作业、高风险工序并行和停机窗口内的组织压力。',
                    forceLevel='should',
                    applicability='construction_org',
                ),
            ],
            severityMapping={
                'construction_org_structure_completeness': 'high',
                'construction_org_duplicate_sections': 'medium',
                'construction_org_shutdown_resource_conflict': 'medium',
            },
            ruleIds=['construction_org_structure_completeness', 'construction_org_duplicate_sections', 'construction_org_shutdown_resource_conflict'],
        ),
        'construction_scheme.base': EvidencePack(
            id='construction_scheme.base',
            version='1.0.0',
            docTypes=['construction_scheme'],
            applicability='construction_scheme',
            clauses=[
                PolicyClause(
                    id='construction_scheme_structure',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='一般施工方案最小结构要求',
                    excerpt='施工方案至少应覆盖工程概况、编制依据、施工方法和安全措施，便于审查其适用边界与执行要求。',
                    forceLevel='should',
                    applicability='construction_scheme',
                )
            ],
            severityMapping={
                'construction_scheme_structure_completeness': 'high',
                'construction_scheme_attachment_visibility': 'medium',
            },
            ruleIds=['construction_scheme_structure_completeness', 'construction_scheme_attachment_visibility'],
        ),
        'hazardous_special_scheme.base': EvidencePack(
            id='hazardous_special_scheme.base',
            version='1.0.0',
            docTypes=['hazardous_special_scheme'],
            applicability='hazardous_special_scheme',
            clauses=[
                PolicyClause(
                    id='dangerous_special_scheme',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='危大工程专项方案要求',
                    excerpt='识别到起重吊装、临时用电、动火等高风险作业后，应明确专项施工方案的适用范围、工艺安排、验算和控制措施。',
                    forceLevel='must',
                    applicability='hazardous_work',
                ),
                PolicyClause(
                    id='hazardous_scheme_structure',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='专项方案核心章节',
                    excerpt='专项施工方案通常应包含工程概况、编制依据、施工计划、施工工艺、安全保证措施、监测监控、应急处置和验算书。',
                    forceLevel='must',
                    applicability='hazardous_special_scheme',
                ),
                PolicyClause(
                    id='hazardous_scheme_calculation',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='专项方案验算与计算',
                    excerpt='涉及起重吊装、支撑体系、受力稳定或设备选型时，应形成可追溯的验算或计算依据。',
                    forceLevel='must',
                    applicability='hazardous_special_scheme',
                ),
                PolicyClause(
                    id='hazardous_scheme_measures',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='风险措施与监测监控',
                    excerpt='专项方案应将主要危险源、控制措施、监测监控和应急处置形成闭环，便于现场执行。',
                    forceLevel='should',
                    applicability='hazardous_special_scheme',
                ),
                PolicyClause(
                    id='hazardous_scheme_drawings',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='专项方案相关图纸',
                    excerpt='专项施工方案应附计算书及相关施工图纸，图纸未进入可视域时应先进入人工复核。',
                    forceLevel='should',
                    applicability='hazardous_special_scheme',
                ),
            ],
            severityMapping={
                'hazardous_special_scheme_core_sections': 'high',
                'hazardous_special_scheme_staffing_completeness': 'medium',
                'hazardous_special_scheme_acceptance_completeness': 'medium',
                'hazardous_special_scheme_drawing_visibility': 'medium',
                'hazardous_special_scheme_risk_identification_completeness': 'medium',
                'hazardous_special_scheme_layout_and_environment_completeness': 'medium',
                'hazardous_special_scheme_calculation_evidence': 'high',
                'lifting_installation_removal_scheme_integrity': 'high',
                'lifting_installation_removal_site_bearing_traceability': 'high',
                'lifting_installation_removal_temporary_fixation_completeness': 'high',
                'lifting_installation_removal_drawing_visibility': 'medium',
                'lifting_operations_special_scheme_linkage': 'high',
                'lifting_operations_calculation_traceability': 'high',
                'temporary_power_control_linkage': 'medium',
                'hot_work_emergency_targeted': 'medium',
                'hazardous_special_scheme_measure_linkage': 'medium',
                'hazardous_special_scheme_emergency_targeted': 'medium',
            },
            ruleIds=[
                'hazardous_special_scheme_core_sections',
                'hazardous_special_scheme_staffing_completeness',
                'hazardous_special_scheme_acceptance_completeness',
                'hazardous_special_scheme_drawing_visibility',
                'hazardous_special_scheme_risk_identification_completeness',
                'hazardous_special_scheme_layout_and_environment_completeness',
                'hazardous_special_scheme_calculation_evidence',
                'lifting_installation_removal_scheme_integrity',
                'lifting_installation_removal_site_bearing_traceability',
                'lifting_installation_removal_temporary_fixation_completeness',
                'lifting_installation_removal_drawing_visibility',
                'lifting_operations_special_scheme_linkage',
                'lifting_operations_calculation_traceability',
                'temporary_power_control_linkage',
                'hot_work_emergency_targeted',
                'hazardous_special_scheme_measure_linkage',
                'hazardous_special_scheme_emergency_targeted',
            ],
        ),
        'foundation_pit.base': EvidencePack(
            id='foundation_pit.base',
            version='1.0.0',
            docTypes=['hazardous_special_scheme'],
            applicability='hazardous_special_scheme',
            clauses=[
                PolicyClause(
                    id='foundation_pit_structure',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='基坑工程专项补充目录要求',
                    excerpt='基坑工程专项方案除通用目录外，还应体现支护/降水/开挖及加撑关系、监测监控、周边环境与监测点相关图纸及验收要求。',
                    forceLevel='must',
                    applicability='foundation_pit',
                ),
                PolicyClause(
                    id='foundation_pit_monitoring',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='基坑监测与图纸要求',
                    excerpt='基坑工程专项方案通常应明确监测监控措施，并附周边环境、监测点和施工顺序等相关图纸。',
                    forceLevel='should',
                    applicability='foundation_pit',
                ),
                PolicyClause(
                    id='foundation_pit_sequence',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='基坑支护降水开挖关系',
                    excerpt='基坑工程应明确支护、地下水控制、土方开挖与加撑之间的关系和施工顺序。',
                    forceLevel='must',
                    applicability='foundation_pit',
                ),
                PolicyClause(
                    id='foundation_pit_acceptance',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='基坑验收要求',
                    excerpt='基坑工程应明确位移、沉降、轴力、排水和侧壁完整性等关键验收内容。',
                    forceLevel='should',
                    applicability='foundation_pit',
                ),
            ],
            severityMapping={
                'foundation_pit_structure_completeness': 'high',
                'foundation_pit_monitoring_and_drawings': 'medium',
                'foundation_pit_support_sequence_integrity': 'high',
                'foundation_pit_acceptance_completeness': 'medium',
            },
            ruleIds=[
                'foundation_pit_structure_completeness',
                'foundation_pit_monitoring_and_drawings',
                'foundation_pit_support_sequence_integrity',
                'foundation_pit_acceptance_completeness',
            ],
        ),
        'formwork_support.base': EvidencePack(
            id='formwork_support.base',
            version='1.0.0',
            docTypes=['hazardous_special_scheme'],
            applicability='hazardous_special_scheme',
            clauses=[
                PolicyClause(
                    id='formwork_support_structure',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='模板支撑体系专项补充目录要求',
                    excerpt='模板支撑体系专项方案除通用目录外，还应体现技术参数、工艺流程/浇筑顺序、计算依据和验收要求。',
                    forceLevel='must',
                    applicability='formwork_support',
                ),
                PolicyClause(
                    id='formwork_support_process',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='模板支撑参数与工艺要求',
                    excerpt='模板支撑体系专项方案应明确技术参数、工艺流程、支架预压方案及混凝土浇筑方式顺序。',
                    forceLevel='must',
                    applicability='formwork_support',
                ),
                PolicyClause(
                    id='formwork_support_calculation',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='模板支撑计算痕迹',
                    excerpt='模板支撑体系应形成强度、刚度、稳定性和基础承载力等计算依据。',
                    forceLevel='must',
                    applicability='formwork_support',
                ),
                PolicyClause(
                    id='formwork_support_acceptance',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='模板支撑验收要求',
                    excerpt='模板支撑体系应明确材料构配件、支撑构造、阶段搭设质量和场地稳定性等验收内容。',
                    forceLevel='should',
                    applicability='formwork_support',
                ),
            ],
            severityMapping={
                'formwork_support_structure_completeness': 'high',
                'formwork_support_process_parameters': 'high',
                'formwork_support_calculation_traceability': 'high',
                'formwork_support_acceptance_completeness': 'medium',
            },
            ruleIds=[
                'formwork_support_structure_completeness',
                'formwork_support_process_parameters',
                'formwork_support_calculation_traceability',
                'formwork_support_acceptance_completeness',
            ],
        ),

        'lifting_installation_removal.base': EvidencePack(
            id='lifting_installation_removal.base',
            version='1.0.0',
            docTypes=['hazardous_special_scheme'],
            applicability='hazardous_special_scheme',
            clauses=[
                PolicyClause(
                    id='lifting_installation_removal_scheme',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='起重吊装及安装拆卸方案骨架',
                    excerpt='起重吊装及安装拆卸工程专项方案应明确设备参数、吊装流程、安装拆卸顺序和作业方法。',
                    forceLevel='must',
                    applicability='lifting_installation_removal',
                ),
                PolicyClause(
                    id='lifting_installation_removal_site_bearing',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='起重站位承载要求',
                    excerpt='起重吊装及安装拆卸工程应明确站位处地基或支承面的承载能力及相关验算痕迹。',
                    forceLevel='must',
                    applicability='lifting_installation_removal',
                ),
                PolicyClause(
                    id='lifting_installation_removal_fixation',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='起重临时固定与辅助装置',
                    excerpt='起重吊装及安装拆卸工程应明确临时固定、缆风绳、地锚、平衡梁、吊索具等稳定装置。',
                    forceLevel='must',
                    applicability='lifting_installation_removal',
                ),
                PolicyClause(
                    id='lifting_installation_removal_drawings',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='起重吊装图纸要求',
                    excerpt='起重吊装及安装拆卸工程通常应附站位图、平立面关系图及复杂条件剖面图，图纸不可视时应人工复核。',
                    forceLevel='should',
                    applicability='lifting_installation_removal',
                ),
            ],
            severityMapping={
                'lifting_installation_removal_scheme_integrity': 'high',
                'lifting_installation_removal_site_bearing_traceability': 'high',
                'lifting_installation_removal_temporary_fixation_completeness': 'high',
                'lifting_installation_removal_drawing_visibility': 'medium',
            },
            ruleIds=[
                'lifting_installation_removal_scheme_integrity',
                'lifting_installation_removal_site_bearing_traceability',
                'lifting_installation_removal_temporary_fixation_completeness',
                'lifting_installation_removal_drawing_visibility',
            ],
        ),
        'scaffold.base': EvidencePack(
            id='scaffold.base',
            version='1.0.0',
            docTypes=['hazardous_special_scheme'],
            applicability='hazardous_special_scheme',
            clauses=[
                PolicyClause(
                    id='scaffold_structure',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='脚手架结构参数',
                    excerpt='脚手架工程专项方案应明确架体类型、高度、基础和主要构造参数。',
                    forceLevel='must',
                    applicability='scaffold',
                ),
                PolicyClause(
                    id='scaffold_safety',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='脚手架连墙件与防护装置',
                    excerpt='脚手架工程应明确连墙件、附着支撑及防倾覆、防坠落等安全装置。',
                    forceLevel='must',
                    applicability='scaffold',
                ),
                PolicyClause(
                    id='scaffold_monitoring_acceptance',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='脚手架监测与验收',
                    excerpt='脚手架工程应明确监测项目、控制值和关键验收内容。',
                    forceLevel='should',
                    applicability='scaffold',
                ),
            ],
            severityMapping={
                'scaffold_structure_parameters_completeness': 'high',
                'scaffold_safety_device_and_wall_tie_completeness': 'high',
                'scaffold_monitoring_and_acceptance_completeness': 'medium',
            },
            ruleIds=[
                'scaffold_structure_parameters_completeness',
                'scaffold_safety_device_and_wall_tie_completeness',
                'scaffold_monitoring_and_acceptance_completeness',
            ],
        ),
        'demolition.base': EvidencePack(
            id='demolition.base',
            version='1.0.0',
            docTypes=['hazardous_special_scheme'],
            applicability='hazardous_special_scheme',
            clauses=[
                PolicyClause(
                    id='demolition_sequence',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='拆除顺序与流程',
                    excerpt='拆除工程专项方案应明确拆除顺序、解体清运流程及关键步序控制。',
                    forceLevel='must',
                    applicability='demolition',
                ),
                PolicyClause(
                    id='demolition_retained_structure',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='保留结构与平台控制',
                    excerpt='拆除工程应明确保留结构、作业平台承载和稳定状态控制要求。',
                    forceLevel='must',
                    applicability='demolition',
                ),
                PolicyClause(
                    id='demolition_calculation',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='拆除临时支撑和吊运计算',
                    excerpt='拆除工程应形成临时支撑、吊运或爆破等计算依据。',
                    forceLevel='must',
                    applicability='demolition',
                ),
            ],
            severityMapping={
                'demolition_sequence_integrity': 'high',
                'demolition_retained_structure_control_completeness': 'high',
                'demolition_support_calculation_traceability': 'high',
            },
            ruleIds=[
                'demolition_sequence_integrity',
                'demolition_retained_structure_control_completeness',
                'demolition_support_calculation_traceability',
            ],
        ),
        'underground_excavation.base': EvidencePack(
            id='underground_excavation.base',
            version='1.0.0',
            docTypes=['hazardous_special_scheme'],
            applicability='hazardous_special_scheme',
            clauses=[
                PolicyClause(
                    id='underground_excavation_water_control',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='暗挖地下水控制',
                    excerpt='暗挖工程专项方案应明确地下水控制、注浆、冻结或相关水处理措施。',
                    forceLevel='must',
                    applicability='underground_excavation',
                ),
                PolicyClause(
                    id='underground_excavation_support_parameters',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='暗挖支护参数',
                    excerpt='暗挖工程应明确开挖进尺、断面尺寸、支护参数和关键工装参数。',
                    forceLevel='must',
                    applicability='underground_excavation',
                ),
                PolicyClause(
                    id='underground_excavation_monitoring',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='暗挖监测与图纸',
                    excerpt='暗挖工程通常应附监测点布置图和周边环境平剖面图，图纸不可视时应人工复核。',
                    forceLevel='should',
                    applicability='underground_excavation',
                ),
            ],
            severityMapping={
                'underground_excavation_water_control_completeness': 'high',
                'underground_excavation_support_parameters_completeness': 'high',
                'underground_excavation_monitoring_and_drawings': 'medium',
            },
            ruleIds=[
                'underground_excavation_water_control_completeness',
                'underground_excavation_support_parameters_completeness',
                'underground_excavation_monitoring_and_drawings',
            ],
        ),
        'curtain_wall_installation.base': EvidencePack(
            id='curtain_wall_installation.base',
            version='1.0.0',
            docTypes=['hazardous_special_scheme'],
            applicability='hazardous_special_scheme',
            clauses=[
                PolicyClause(
                    id='curtain_wall_installation_facility',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='幕墙安装设施与防护',
                    excerpt='建筑幕墙安装工程应明确安装操作设施、附着支座、动力设备及安全防护设置。',
                    forceLevel='must',
                    applicability='curtain_wall_installation',
                ),
                PolicyClause(
                    id='curtain_wall_installation_route_layout',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='幕墙运输路线和平面布置',
                    excerpt='建筑幕墙安装工程应明确运输路线、吊装运行路线和堆放平面布置。',
                    forceLevel='should',
                    applicability='curtain_wall_installation',
                ),
                PolicyClause(
                    id='curtain_wall_installation_drawings',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='幕墙安装图纸与验收',
                    excerpt='建筑幕墙安装工程通常应附相关图纸并明确验收要求，图纸未进入可视域时应人工复核。',
                    forceLevel='should',
                    applicability='curtain_wall_installation',
                ),
            ],
            severityMapping={
                'curtain_wall_installation_facility_integrity': 'high',
                'curtain_wall_installation_route_and_layout_completeness': 'medium',
                'curtain_wall_installation_drawing_and_acceptance': 'medium',
            },
            ruleIds=[
                'curtain_wall_installation_facility_integrity',
                'curtain_wall_installation_route_and_layout_completeness',
                'curtain_wall_installation_drawing_and_acceptance',
            ],
        ),
        'manual_bored_pile.base': EvidencePack(
            id='manual_bored_pile.base',
            version='1.0.0',
            docTypes=['hazardous_special_scheme'],
            applicability='hazardous_special_scheme',
            clauses=[
                PolicyClause(
                    id='manual_bored_pile_jump_excavation',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='人工挖孔桩跳挖组织',
                    excerpt='人工挖孔桩工程应明确跳挖、分区分序等作业组织要求。',
                    forceLevel='must',
                    applicability='manual_bored_pile',
                ),
                PolicyClause(
                    id='manual_bored_pile_gas_electric_safety',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='人工挖孔桩防中毒触电',
                    excerpt='人工挖孔桩工程应明确有害气体检测、防中毒窒息和防触电措施。',
                    forceLevel='must',
                    applicability='manual_bored_pile',
                ),
                PolicyClause(
                    id='manual_bored_pile_forbidden_conditions',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='人工挖孔桩禁用条件',
                    excerpt='人工挖孔桩涉及禁用条件时，应结合工程地质、水文和现场条件进行人工确认，不宜直接自动下结论。',
                    forceLevel='should',
                    applicability='manual_bored_pile',
                ),
            ],
            severityMapping={
                'manual_bored_pile_jump_excavation_integrity': 'high',
                'manual_bored_pile_gas_and_electric_safety_completeness': 'high',
                'manual_bored_pile_forbidden_conditions_manual_review': 'high',
            },
            ruleIds=[
                'manual_bored_pile_jump_excavation_integrity',
                'manual_bored_pile_gas_and_electric_safety_completeness',
                'manual_bored_pile_forbidden_conditions_manual_review',
            ],
        ),
        'steel_structure_installation.base': EvidencePack(
            id='steel_structure_installation.base',
            version='1.0.0',
            docTypes=['hazardous_special_scheme'],
            applicability='hazardous_special_scheme',
            clauses=[
                PolicyClause(
                    id='steel_structure_installation_structure',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='钢结构安装专项补充目录要求',
                    excerpt='钢结构安装专项方案除通用目录外，还应体现构件参数、吊装设备选型、安装流程、拼装胎架/临时支撑/卸载条件及措施图纸和验收章节。',
                    forceLevel='must',
                    applicability='steel_structure_installation',
                ),
                PolicyClause(
                    id='steel_structure_installation_scheme',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='钢结构安装吊装方案',
                    excerpt='钢结构安装专项方案应明确构件参数、吊装设备选型、安装流程和站位路线等关键信息。',
                    forceLevel='must',
                    applicability='steel_structure_installation',
                ),
                PolicyClause(
                    id='steel_structure_installation_support',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='钢结构临时支撑与卸载',
                    excerpt='钢结构安装专项方案应明确拼装胎架、临时支撑、卸载条件及相关工装措施。',
                    forceLevel='must',
                    applicability='steel_structure_installation',
                ),
                PolicyClause(
                    id='steel_structure_installation_drawings',
                    sourceId='construction-《危险性较大的分部分项工程专项施工方案编制指南》（建办质〔2021〕48号）',
                    title='钢结构措施图纸与验收',
                    excerpt='钢结构安装专项方案应附相关措施施工图，并明确吊装、索具、胎架和卸载等验收内容；图纸不清时应人工复核。',
                    forceLevel='should',
                    applicability='steel_structure_installation',
                ),
            ],
            severityMapping={
                'steel_structure_installation_structure_completeness': 'high',
                'steel_structure_installation_lifting_scheme_integrity': 'high',
                'steel_structure_installation_support_and_unloading': 'high',
                'steel_structure_installation_drawing_and_acceptance': 'medium',
            },
            ruleIds=[
                'steel_structure_installation_structure_completeness',
                'steel_structure_installation_lifting_scheme_integrity',
                'steel_structure_installation_support_and_unloading',
                'steel_structure_installation_drawing_and_acceptance',
            ],
        ),
        'supervision_plan.base': EvidencePack(
            id='supervision_plan.base',
            version='1.0.0',
            docTypes=['supervision_plan'],
            applicability='supervision_plan',
            clauses=[
                PolicyClause(
                    id='supervision_plan_structure',
                    sourceId='construction-《建设工程监理规范》GB/T 50319',
                    title='监理规划基础结构',
                    excerpt='监理规划至少应交代工程概况、编制依据和监理控制措施，以支持后续旁站、巡视和验收控制。',
                    forceLevel='should',
                    applicability='supervision_plan',
                ),
                PolicyClause(
                    id='supervision_plan_monitoring',
                    sourceId='construction-《建设工程监理规范》GB/T 50319',
                    title='监测监控与旁站安排',
                    excerpt='监理规划或实施细则应明确监测监控、旁站和巡视检查的触发条件、责任与记录要求。',
                    forceLevel='should',
                    applicability='supervision_plan',
                ),
            ],
            severityMapping={
                'supervision_plan_structure_completeness': 'medium',
                'supervision_plan_monitoring_linkage': 'medium',
                'supervision_plan_attachment_visibility': 'medium',
            },
            ruleIds=[
                'supervision_plan_structure_completeness',
                'supervision_plan_monitoring_linkage',
                'supervision_plan_attachment_visibility',
            ],
        ),
        'review_support_material.base': EvidencePack(
            id='review_support_material.base',
            version='1.0.0',
            docTypes=['review_support_material'],
            applicability='review_support_material',
            clauses=[
                PolicyClause(
                    id='review_support_material_context',
                    sourceId='review-control-plane-support-scope-policy',
                    title='审查支持材料边界',
                    excerpt='审查支持材料只能补充背景或辅助判断，不能替代正式施工组织设计、施工方案或专项方案正文。',
                    forceLevel='guidance',
                    applicability='review_support_material',
                )
            ],
            severityMapping={
                'review_support_material_context_only': 'low',
                'review_support_material_attachment_visibility': 'low',
            },
            ruleIds=['review_support_material_context_only', 'review_support_material_attachment_visibility'],
        ),
        'distribution_network_special_scheme.base': EvidencePack(
            id='distribution_network_special_scheme.base',
            version='1.0.0',
            docTypes=['distribution_network_special_scheme'],
            applicability='distribution_network_special_scheme',
            clauses=[
                PolicyClause(
                    id='distribution_network_special_scheme_structure',
                    sourceId='review-control-plane-special-scheme-structure-policy',
                    title='配网工程专项施工方案通用目录要求',
                    excerpt='配网工程专项施工方案除专项补充要求外，仍应覆盖工程概况、编制依据、施工计划、施工工艺技术、施工保证措施、人员分工、验收要求、应急处置、图纸、风险辨识、平面布置或周边环境、计算与验算依据等通用内容。',
                    forceLevel='should',
                    applicability='distribution_network_special_scheme',
                ),
            ],
            severityMapping={
                'distribution_network_special_scheme_structure_completeness': 'medium',
            },
            ruleIds=['distribution_network_special_scheme_structure_completeness'],
        ),
        'power_outage_work.base': EvidencePack(
            id='power_outage_work.base',
            version='1.0.0',
            docTypes=['distribution_network_special_scheme'],
            applicability='power_outage_work',
            clauses=[
                PolicyClause(
                    id='power_outage_work_structure',
                    sourceId='review-control-plane-special-scheme-structure-policy',
                    title='停电施工作业专项补充目录要求',
                    excerpt='停电施工作业专项施工方案除专项施工方案通用要求外，还应覆盖停电范围、作业内容、主要风险、施工人员、机具、材料、安全管控、质量管控、应急措施等响应内容；不要求完全同名或同层级，但正文应有稳定支撑内容。',
                    forceLevel='should',
                    applicability='power_outage_work',
                ),
            ],
            severityMapping={
                'power_outage_work_structure_completeness': 'high',
                'temporary_power_control_linkage': 'medium',
            },
            ruleIds=['power_outage_work_structure_completeness', 'temporary_power_control_linkage'],
        ),
        'review.visibility': EvidencePack(
            id='review.visibility',
            version='1.0.0',
            docTypes=['construction_org', 'construction_scheme', 'hazardous_special_scheme', 'distribution_network_special_scheme', 'supervision_plan', 'review_support_material'],
            applicability='all_review_types',
            clauses=[
                PolicyClause(
                    id='review_visibility_gap',
                    sourceId='review-control-plane-visibility-policy',
                    title='附件可视域处理',
                    excerpt='当附件或图纸未进入当前解析可视域时，应标记为 visibility_gap / manual_review_needed，而不是直接判定缺失。',
                    forceLevel='guidance',
                    applicability='all_review_types',
                )
            ],
            severityMapping={
                'construction_org_attachment_visibility': 'medium',
                'hazardous_special_scheme_attachment_visibility': 'medium',
            },
            ruleIds=['construction_org_attachment_visibility', 'hazardous_special_scheme_attachment_visibility'],
        ),
        'review.emergency': EvidencePack(
            id='review.emergency',
            version='1.0.0',
            docTypes=['construction_org', 'hazardous_special_scheme', 'distribution_network_special_scheme'],
            applicability='construction_and_hazardous',
            clauses=[
                PolicyClause(
                    id='emergency_plan_targeted',
                    sourceId='construction-《建设工程安全生产管理条例》',
                    title='应急预案针对性',
                    excerpt='应急管理文件应与主要危险源相匹配，便于事故类型、联系链路和现场处置动作快速落地。',
                    forceLevel='should',
                    applicability='construction_org,hazardous_special_scheme',
                )
            ],
            severityMapping={
                'construction_org_emergency_plan_targeted': 'medium',
                'hazardous_special_scheme_emergency_targeted': 'medium',
                'temporary_power_control_linkage': 'medium',
                'hot_work_emergency_targeted': 'medium',
                'gas_area_ops_control_linkage': 'high',
            },
            ruleIds=[
                'construction_org_emergency_plan_targeted',
                'hazardous_special_scheme_emergency_targeted',
                'temporary_power_control_linkage',
                'hot_work_emergency_targeted',
                'gas_area_ops_control_linkage',
            ],
        ),
    }
    return {pack_id: _load_manifest_pack(pack_id, pack) for pack_id, pack in registry.items()}


def _load_manifest_pack(pack_id: str, fallback: EvidencePack) -> EvidencePack:
    manifest_path = _evidence_manifest_dir() / f'{pack_id}.json'
    if not manifest_path.exists():
        return fallback
    try:
        payload = json.loads(manifest_path.read_text(encoding='utf-8'))
        return EvidencePack.model_validate(payload)
    except Exception:
        return fallback


def _evidence_manifest_dir() -> Path:
    return Path(__file__).resolve().parents[5] / 'fixtures' / 'construction' / 'derived' / 'evidence_packs'
